# docker-compose를 만드는 순간 네트워크 자동 생성 및 연결

version: "3.7"

services:
  db:  # container name
    image: mysql:5.7
    volumes:  # /var/lib/mysql과 호스트의 ./db_data를 연결
      - ./db_data:/var/lib/mysql
    restart: always
    environment:  # 환경변수 설정
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 123456
  
  app:
    depends_on:  # db 컨테이너가 먼저 만들어지고 app 컨테이너가 만들어지도록 함
      - db
    image: wordpress:latest
    volumes:
      - ./app_data:/var/www/html
    ports:  # 8080포트로는 80포트인 app 컨테이너에 접근 가능 (db 컨테이너는 외부에서 접근할 필요가 없으므로 포트 설정 X)
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306  # 같은 네트워크에 속해있는 db 컨테이너의 3306포트로 접근
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 123456 
